- name: Creates directory for wallpaper
  file:
    path: /home/pi/appearance
    state: directory

- name: copy wallpaper
  copy:
    src: ./files/wallpaper.jpg
    dest: /home/pi/appearance

- name: set wallpaper
  shell:
    cmd: pcmanfm --set-wallpaper="/home/pi/appearance/wallpaper.jpg"
